# -*- coding: utf-8 -*-
"""UTS_business_intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYKaZYl1HR9_TB3DCYcBbwbs07BN-d-o

# Proses ETL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

"""## Extract"""

df = pd.read_csv('/hotel_booking.csv')

print("=" * 80)
print("1. EXTRACT - HASIL PEMBACAAN DATASET")
print("=" * 80)

print("\n--- a. head() - 5 Baris Pertama ---")
print(df.head())

print("\n--- b. info() - Informasi Dataset ---")
print(df.info())

print("\n--- c. describe() - Statistik Deskriptif ---")
print(df.describe())

print("\n--- d. Shape Dataset ---")
print(f"Jumlah Baris: {df.shape[0]}")
print(f"Jumlah Kolom: {df.shape[1]}")

from google.colab import drive
drive.mount('/content/drive')

"""## Data Understanding

### 2.1 Identifikasi Missing Value
"""

# 2.1 Identifikasi Missing Value
print("\n--- a. Missing Value Analysis ---")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing Percentage (%)': missing_pct
})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing Count', ascending=False)
print(missing_df)

"""### 2.2 Identifikasi Tipe Data"""

# 2.2 Identifikasi Tipe Data
print("\n--- b. Tipe Data per Kolom ---")
dtype_df = pd.DataFrame({
    'Kolom': df.columns,
    'Tipe Data': df.dtypes.values,
    'Non-Null Count': df.count().values
})
print(dtype_df.to_string(index=False))

"""### 2.3 Kolom-kolom Penting"""

# 2.3 Kolom-kolom Penting
print("\n--- c. Penjelasan Kolom-Kolom Penting ---")
kolom_penting = {
    'hotel': 'Jenis hotel (Resort Hotel / City Hotel)',
    'is_canceled': 'Status pembatalan (0 = tidak dibatalkan, 1 = dibatalkan)',
    'lead_time': 'Jumlah hari antara booking dan kedatangan',
    'arrival_date_year/month/week_number/day_of_month': 'Tanggal kedatangan tamu',
    'stays_in_weekend_nights': 'Jumlah malam menginap di akhir pekan',
    'stays_in_week_nights': 'Jumlah malam menginap di hari kerja',
    'adults/children/babies': 'Jumlah tamu dewasa, anak, dan bayi',
    'meal': 'Tipe paket makan (BB, HB, FB, SC)',
    'country': 'Negara asal tamu',
    'market_segment': 'Segmen pasar (Online TA, Direct, Corporate, dll)',
    'distribution_channel': 'Kanal distribusi booking',
    'adr': 'Average Daily Rate - tarif rata-rata per malam',
    'required_car_parking_spaces': 'Jumlah tempat parkir yang dibutuhkan',
    'total_of_special_requests': 'Jumlah permintaan khusus tamu',
    'reservation_status': 'Status reservasi (Check-Out, Canceled, No-Show)',
    'reservation_status_date': 'Tanggal status reservasi terakhir',
    'customer_type': 'Tipe pelanggan (Transient, Contract, Group, dll)'
}
for k, v in kolom_penting.items():
    print(f"  • {k}: {v}")

"""### 2.4 Potensi Masalah Data"""

# 2.4 Potensi Masalah Data
print("\n--- d. Potensi Masalah Data ---")
print("1. Missing Value:")
print(f"   - children: {df['children'].isnull().sum()} missing ({(df['children'].isnull().sum()/len(df)*100):.2f}%)")
print(f"   - country: {df['country'].isnull().sum()} missing ({(df['country'].isnull().sum()/len(df)*100):.2f}%)")
print(f"   - agent: {df['agent'].isnull().sum()} missing ({(df['agent'].isnull().sum()/len(df)*100):.2f}%)")
print(f"   - company: {df['company'].isnull().sum()} missing ({(df['company'].isnull().sum()/len(df)*100):.2f}%)")

print("\n2. Data Tidak Valid:")
print(f"   - adr < 0: {(df['adr'] < 0).sum()} baris")
print(f"   - adr = 0: {(df['adr'] == 0).sum()} baris")
print(f"   - adults = 0: {(df['adults'] == 0).sum()} baris")
print(f"   - total_nights = 0 (weekend + weekday = 0): {((df['stays_in_weekend_nights'] + df['stays_in_week_nights']) == 0).sum()} baris")

print("\n3. Tipe Data yang Perlu Diubah:")
print("   - reservation_status_date: object → datetime")
print("   - children: float64 → int64")
print("   - agent, company: float64 → object/string (kode ID)")

print("\n4. Data Duplikat:")
duplicates = df.duplicated().sum()
print(f"   - Jumlah baris duplikat: {duplicates}")

"""## Transform

### Membuat salinan untuk transformasi
"""

# 3. TRANSFORM - Membuat salinan untuk transformasi
df_clean = df.copy()

"""### Data Cleaning

#### Missing Value
"""

# children: 4 missing → isi dengan 0 (asumsi tidak ada anak)
print(f"\n  • children: {df_clean['children'].isnull().sum()} missing → diisi dengan 0")
print("    Alasan: Jumlah anak yang kosong diasumsikan 0 (tidak membawa anak)")
df_clean['children'] = df_clean['children'].fillna(0)

# country: 488 missing → isi dengan 'Unknown'
print(f"\n  • country: {df_clean['country'].isnull().sum()} missing → diisi dengan 'Unknown'")
print("    Alasan: Negara tidak diketahui, tidak boleh dihapus karena data lain valid")
df_clean['country'] = df_clean['country'].fillna('Unknown')

# agent: 16340 missing → isi dengan 'No Agent'
print(f"\n  • agent: {df_clean['agent'].isnull().sum()} missing → diisi dengan 'No Agent'")
print("    Alasan: Booking tanpa agent (Direct booking) adalah kategori valid")
df_clean['agent'] = df_clean['agent'].fillna('No Agent')

# company: 112593 missing (94.3%) → Drop kolom karena terlalu banyak missing
print(f"\n  • company: {df_clean['company'].isnull().sum()} missing ({(df_clean['company'].isnull().sum()/len(df_clean)*100):.1f}%)")
print("    Alasan: 94.3% data kosong, kolom ini tidak informatif untuk analisis BI")
print("    Keputusan: DROP kolom 'company'")
df_clean = df_clean.drop('company', axis=1)

print(f"\n Setelah pembersihan: Missing value tersisa = {df_clean.isnull().sum().sum()}")

"""#### Menghapus Data Tidak Valid

ALASAN DATA INVALID HARUS DIHAPUS:

1. KUALITAS DATA (DATA QUALITY): Data warehouse memerlukan data yang
   representatif dan akurat. Data invalid adalah noise yang merusak analisis.

2. AKURASI KPI: ADR (Average Daily Rate) <= 0 berarti hotel tidak mendapat
   revenue. Jika disertakan, KPI "Total Revenue" dan "RevPAR" akan salah.

3. ANALISIS PREDIKTIF: Model machine learning untuk prediksi cancellation
   atau demand forecasting akan terpengaruh negatif oleh outlier invalid.

4. REPORTING FINANSIAL: Laporan keuangan untuk stakeholder tidak boleh
   mencakup transaksi dengan nilai negatif atau nol yang tidak masuk akal.

5. DDS INTEGRITY: Fact table dalam DDS menyimpan measures (fact) yang harus
   valid. Invalid measures akan merusak rollup dan drill-down operations.
"""

# Cek data invalid sebelum penghapusan
invalid_adr_neg = (df_clean['adr'] < 0).sum()
invalid_adr_zero = (df_clean['adr'] == 0).sum()
invalid_adults_zero = (df_clean['adults'] == 0).sum()
invalid_nights_zero = ((df_clean['stays_in_weekend_nights'] + df_clean['stays_in_week_nights']) == 0).sum()

print(f"\n  • adr < 0 (negative): {invalid_adr_neg} baris")
print(f"    Contoh: adr = -{df_clean[df_clean['adr'] < 0]['adr'].abs().max() if invalid_adr_neg > 0 else 'N/A'}")
print(f"    Dampak: Revenue negatif → Total Revenue salah → Laporan keuangan invalid")

print(f"\n  • adr = 0 (zero): {invalid_adr_zero} baris")
print(f"    Dampak: Revenue nol untuk booking yang valid → RevPAR = 0 →")
print(f"           Analisis profitabilitas hotel menjadi tidak akurat")

print(f"\n  • adults = 0: {invalid_adults_zero} baris")
print(f"    Dampak: Booking tanpa tamu dewasa adalah data anomali →")
print(f"           Occupancy rate dan ADR per tamu menjadi tidak valid")

print(f"\n  • total_nights = 0: {invalid_nights_zero} baris")
print(f"    Dampak: Booking tanpa menginap → Length of Stay (LOS) = 0 →")
print(f"           Analisis durasi menginap dan revenue per night gagal")

# Hapus adr < 0
print(f"\n  Step 1: Hapus adr < 0 → {invalid_adr_neg} baris dihapus")
df_clean = df_clean[df_clean['adr'] >= 0]

# Hapus adults = 0
print(f"  Step 2: Hapus adults = 0 → {invalid_adults_zero} baris dihapus")
df_clean = df_clean[df_clean['adults'] > 0]

# Hapus total nights = 0 (kecuali untuk canceled bookings yang mungkin valid)
# Namun untuk DDS, kita hanya simpan data dengan nights > 0 untuk analisis menginap
print(f"  Step 3: Hapus total_nights = 0 → {invalid_nights_zero} baris dihapus")
df_clean = df_clean[(df_clean['stays_in_weekend_nights'] + df_clean['stays_in_week_nights']) > 0]

print(f"\n  Jumlah baris setelah penghapusan: {len(df_clean)}")
print(f"  Total baris dihapus: {len(df) - len(df_clean)}")
print(f"  Persentase data yang dipertahankan: {(len(df_clean)/len(df)*100):.2f}%")

"""#### Menghapus Data Duplikat"""

# Cek duplikat berdasarkan semua kolom
duplicates_all = df_clean.duplicated().sum()
print(f"\n  • Duplikat exact (semua kolom sama): {duplicates_all} baris")

"""### Data Transformation

##### Rename semua kolom ke lowercase
"""

print("\nSebelum:")
print(f"   Kolom sample: {list(df_clean.columns[:5])}")

# Rename semua kolom ke lowercase
df_clean.columns = df_clean.columns.str.lower()

print("\nSesudah:")
print(f"   Kolom sample: {list(df_clean.columns[:5])}")
print(f"\nTotal kolom setelah rename: {len(df_clean.columns)}")

"""##### Mengubah Tipe Data

ALASAN TIPE DATA HARUS SESUAI DALAM DDS:

1. OPTIMALISASI STORAGE: Tipe data yang tepat mengurangi ukuran storage.
   Contoh: int32 vs float64 untuk ID dapat menghemat 50% storage.

2. KECEPATAN QUERY: Database dapat melakukan index dan partition lebih efisien
   pada tipe data yang sesuai. Query pada datetime jauh lebih cepat daripada string.

3. AKURASI AGREGASI: Tipe data numerik memastikan SUM, AVG, MIN, MAX berjalan
   dengan benar. String yang menyimpan angka tidak dapat diagregasi.

4. FILTER & SORTING: Filter tanggal (BETWEEN, >, <) hanya berfungsi pada datetime.
   String comparison pada tanggal menghasilkan hasil yang salah.

5. DASHBOARD BI: Tools BI mengenali tipe data untuk menentukan visualisasi
   yang tepat. Datetime → time series chart, numeric → bar/line chart.

6. FOREIGN KEY INTEGRITY: Dalam DDS, foreign keys harus memiliki tipe data
   yang sama dengan primary key di dimension table untuk join yang valid.
"""

print("\nROSES PERUBAHAN TIPE DATA:")
print("\nSebelum perubahan:")
print(df_clean[['children', 'agent', 'reservation_status_date']].dtypes)

# children: float64 → int64 (jumlah anak harus integer)
print("\n  • children: float64 → int64")
print("    Alasan: Jumlah anak adalah bilangan bulat, tidak ada desimal")
df_clean['children'] = df_clean['children'].astype(int)

# agent: float64 → object/string (kode agent, bukan angka untuk kalkulasi)
print("\n  • agent: float64 → object (string)")
print("    Alasan: 'agent' adalah kode ID, bukan nilai numerik untuk operasi matematika")
df_clean['agent'] = df_clean['agent'].astype(str)

# reservation_status_date: object → datetime
print("\n  • reservation_status_date: object → datetime64")
print("    Alasan: Tanggal memerlukan tipe datetime untuk filter, sorting,")
print("           time-series analysis, dan perhitungan durasi")
df_clean['reservation_status_date'] = pd.to_datetime(df_clean['reservation_status_date'])

print("\nSesudah perubahan:")
print(df_clean[['children', 'agent', 'reservation_status_date']].dtypes)

"""### Feature Engineering

KENAPA FEATURE ENGINEERING PENTING DALAM DDS:

1. PRE-AGGREGATED MEASURES: DDS (Dimensional Data Store) menyimpan data
   dalam bentuk yang siap untuk analisis. Feature engineering membuat
   measures yang sering digunakan dalam query BI menjadi kolom tersendiri.

2. QUERY PERFORMANCE: Kolom yang sering diagregasi (SUM, AVG) sebaiknya
   di-precompute untuk mengurangi waktu query pada data warehouse.

3. BUSINESS SEMANTICS: Kolom seperti 'revenue' dan 'total_nights' memiliki
   makna bisnis yang jelas, memudahkan business user memahami data.

4. STAR SCHEMA DESIGN: Fact table dalam DDS berisi measures (fact) yang
   berasal dari feature engineering. Dimension table berisi attributes.

5. SELF-SERVICE BI: Business user dapat membuat dashboard tanpa menulis
   query kompleks karena measures sudah tersedia sebagai kolom.

#### Membuat Kolom Baru
"""

print("\n📊 KOLOM 1: total_nights")
print("-" * 40)
df_clean['total_nights'] = df_clean['stays_in_weekend_nights'] + df_clean['stays_in_week_nights']
print(f"  Statistik total_nights:")
print(f"  • Min: {df_clean['total_nights'].min()}")
print(f"  • Max: {df_clean['total_nights'].max()}")
print(f"  • Mean: {df_clean['total_nights'].mean():.2f}")
print(f"  • Median: {df_clean['total_nights'].median()}")

# Membuat kolom revenue
print("\n📊 KOLOM 2: revenue")
print("-" * 40)
df_clean['revenue'] = df_clean['adr'] * df_clean['total_nights']
print(f"  Statistik revenue:")
print(f"  • Min: ${df_clean['revenue'].min():.2f}")
print(f"  • Max: ${df_clean['revenue'].max():.2f}")
print(f"  • Mean: ${df_clean['revenue'].mean():.2f}")
print(f"  • Median: ${df_clean['revenue'].median():.2f}")
print(f"  • Total Revenue: ${df_clean['revenue'].sum():,.2f}")

# total_guests
df_clean['total_guests'] = df_clean['adults'] + df_clean['children'] + df_clean['babies']
print("\n  • total_guests = adults + children + babies")
print("    → Measure untuk occupancy analysis dan capacity planning")

# is_family (flag untuk tamu yang membawa anak/bayi)
df_clean['is_family'] = ((df_clean['children'] > 0) | (df_clean['babies'] > 0)).astype(int)
print("\n  • is_family (0/1) = children > 0 OR babies > 0")
print("    → Dimension attribute untuk segmentasi keluarga vs non-keluarga")

# booking_date (estimasi tanggal booking dari lead_time)
# Asumsi: booking_date = arrival_date - lead_time
# Kita perlu membuat arrival_date terlebih dahulu
df_clean['arrival_date'] = pd.to_datetime(
    df_clean['arrival_date_year'].astype(str) + '-' +
    df_clean['arrival_date_month'] + '-' +
    df_clean['arrival_date_day_of_month'].astype(str))
df_clean['booking_date'] = df_clean['arrival_date'] - pd.to_timedelta(df_clean['lead_time'], unit='D')
print("\n  • arrival_date (datetime) = kombinasi year + month + day")
print("    → Dimension key untuk time dimension table")
print("\n  • booking_date (datetime) = arrival_date - lead_time")
print("    → Measure untuk analisis booking pattern dan lead time distribution")

print(f"\nTotal kolom setelah feature engineering: {len(df_clean.columns)}")

"""## Load"""

powerbi_df = df_clean[[
    'hotel',
    'is_canceled',
    'lead_time',
    'arrival_date_year',
    'arrival_date_month',
    'arrival_date_week_number',
    'arrival_date_day_of_month',
    'stays_in_weekend_nights',
    'stays_in_week_nights',
    'adults',
    'children',
    'babies',
    'meal',
    'country',
    'market_segment',
    'distribution_channel',
    'reserved_room_type',
    'assigned_room_type',
    'booking_changes',
    'deposit_type',
    'customer_type',
    'adr',
    'required_car_parking_spaces',
    'total_of_special_requests',
    'total_nights',
    'revenue'
]].copy()

powerbi_df.to_csv(
    'powerbi_hotel.csv',
    index=False
)

"""### Pembuatan Fact Table"""

from google.colab import files

files.download('powerbi_hotel.csv')